import { emstrong } from './emstrong';
import { some } from '../../combinator';
import { input } from '../../combinator/data/parser';
import { Context } from '../context';
import { inspect } from '../../debug.test';

describe('Unit: parser/inline/emstrong', () => {
  describe('emstrong', () => {
    const parser = some(emstrong);

    it('invalid', () => {
      assert.deepStrictEqual(inspect(parser, input('***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***a', new Context())), [['***a'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a ***', new Context())), [['***a ', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a  ***', new Context())), [['***a', ' ', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a\n***', new Context())), [['***a', '<br>', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a\\ ***', new Context())), [['***a', ' ', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a\\\n***', new Context())), [['***a', '<br>', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('*** ***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('*** a***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('*** a ***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***\n***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***\na***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***\\ a***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***\\\na***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('***<wbr>a***', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input(' ***a***', new Context())), undefined);
    });

    it('basic', () => {
      assert.deepStrictEqual(inspect(parser, input('***a***', new Context())), [['<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***ab***', new Context())), [['<em><strong>ab</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a****', new Context())), [['<em><strong>a</strong></em>'], '*']);
      assert.deepStrictEqual(inspect(parser, input('***a\nb***', new Context())), [['<em><strong>a<br>b</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a\\\nb***', new Context())), [['<em><strong>a<br>b</strong></em>'], '']);
    });

    it('nest', () => {
      assert.deepStrictEqual(inspect(parser, input('***`a`***', new Context())), [['<em><strong><code data-src="`a`">a</code></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***(*a*)***', new Context())), [['<em><strong><span class="paren">(<em>a</em>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***(**a**)***', new Context())), [['<em><strong><span class="paren">(<strong>a</strong>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***(***a***)***', new Context())), [['<em><strong><span class="paren">(<em><strong>a</strong></em>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*', new Context())), [['**', '<em>a</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b', new Context())), [['**', '<em>a</em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*', new Context())), [['**', '<em>a</em>', 'b'], '*']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c', new Context())), [['**', '<em>a</em>', 'b', '*', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c*', new Context())), [['**', '<em>a</em>', 'b', '<em>c</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c**', new Context())), [['**', '<em>a</em>', 'b', '<em>c</em>'], '*']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c***', new Context())), [['<strong><em>a</em>b<em>c</em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b**', new Context())), [['<strong><em>a</em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b**c', new Context())), [['<strong><em>a</em>b</strong>'], 'c']);
      assert.deepStrictEqual(inspect(parser, input('***a**', new Context())), [['*', '<strong>a</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b', new Context())), [['*', '<strong>a</strong>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b*', new Context())), [['<em><strong>a</strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**', new Context())), [['<em><strong>a</strong>b</em>'], '*']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c', new Context())), [['*', '<strong>a</strong>', 'b', '**', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c*', new Context())), [['<em><strong>a</strong>b**c</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c**', new Context())), [['*', '<strong>a</strong>', 'b', '<strong>c</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c***', new Context())), [['<em><strong>a</strong>b<strong>c</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a *b****', new Context())), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a\\ *b****', new Context())), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a&Tab;*b****', new Context())), [['<em><strong>a\t<em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a<wbr>*b****', new Context())), [['<em><strong>a<wbr><em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a *b****', new Context())), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a* **b****', new Context())), [['<strong><em>a</em> <strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*\\ **b****', new Context())), [['<strong><em>a</em> <strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*&Tab;**b****', new Context())), [['<strong><em>a</em>\t<strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*<wbr>**b****', new Context())), [['<strong><em>a</em><wbr><strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b **', new Context())), [['**', '<em>a</em>', 'b ', '**'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b\\ **', new Context())), [['**', '<em>a</em>', 'b', ' ', '**'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b*', new Context())), [['<em><strong>a</strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b*c', new Context())), [['<em><strong>a</strong>b</em>'], 'c']);
      assert.deepStrictEqual(inspect(parser, input('***a**b*c**', new Context())), [['<em><strong>a</strong>b</em>'], 'c**']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c***', new Context())), [['<em><strong>a</strong>b<strong>c</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c***d', new Context())), [['<em><strong>a</strong>b<strong>c</strong></em>'], 'd']);
      assert.deepStrictEqual(inspect(parser, input('***a** *b**', new Context())), [['<em><strong>a</strong> <em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**\\ *b**', new Context())), [['<em><strong>a</strong> <em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**&Tab;*b**', new Context())), [['<em><strong>a</strong>\t<em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**<wbr>*b**', new Context())), [['<em><strong>a</strong><wbr><em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b *', new Context())), [['*', '<strong>a</strong>', 'b ', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b\\ *', new Context())), [['*', '<strong>a</strong>', 'b', ' ', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*', new Context())), [['**', '<em>a</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**', new Context())), [['*', '<strong>a</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a***', new Context())), [['<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a***b', new Context())), [['<em><strong>a</strong></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser, input('***a****', new Context())), [['<em><strong>a</strong></em>'], '*']);
      assert.deepStrictEqual(inspect(parser, input('***a*****', new Context())), [['<em><strong>a</strong></em>'], '**']);
      assert.deepStrictEqual(inspect(parser, input('***a******', new Context())), [['<em><strong>a</strong></em>'], '***']);
      assert.deepStrictEqual(inspect(parser, input('****a***', new Context())), [['*', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('****a***b', new Context())), [['*', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('****a***b*', new Context())), [['<em><em><strong>a</strong></em>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('****a****', new Context())), [['<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('****a****b', new Context())), [['<em><em><strong>a</strong></em></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser, input('*****a***', new Context())), [['**', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a***b', new Context())), [['**', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a***b**', new Context())), [['<strong><em><strong>a</strong></em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a****', new Context())), [['*', '<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a****b', new Context())), [['*', '<em><em><strong>a</strong></em></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a****b*', new Context())), [['<em><em><em><strong>a</strong></em></em>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*****a*****', new Context())), [['<strong><em><strong>a</strong></em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a***', new Context())), [['***', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a***b', new Context())), [['***', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a****', new Context())), [['**', '<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a****b', new Context())), [['**', '<em><em><strong>a</strong></em></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a****b**', new Context())), [['<strong><em><em><strong>a</strong></em></em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*****', new Context())), [['*', '<strong><em><strong>a</strong></em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*****b', new Context())), [['*', '<strong><em><strong>a</strong></em></strong>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*****b*', new Context())), [['<em><strong><em><strong>a</strong></em></strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a******', new Context())), [['<em><strong><em><strong>a</strong></em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a******b', new Context())), [['<em><strong><em><strong>a</strong></em></strong></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser, input('******a*b', new Context())), [['*****', '<em>a</em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*b *', new Context())), [['*****', '<em>a</em>', 'b ', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*b **', new Context())), [['*****', '<em>a</em>', 'b ', '**'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*b ***', new Context())), [['*****', '<em>a</em>', 'b ', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*b ****', new Context())), [['*****', '<em>a</em>', 'b ', '****'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*b *****', new Context())), [['*****', '<em>a</em>', 'b ', '*****'], '']);
      assert.deepStrictEqual(inspect(parser, input('******a*** b***', new Context())), [['<em><strong><em><strong>a</strong></em> b</strong></em>'], '']);
    });

  });

});
