import { emstrong } from './emstrong';
import { some } from '../../combinator';
import { input } from '../../combinator/data/parser';
import { inspect } from '../../debug.test';

describe('Unit: parser/inline/emstrong', () => {
  describe('emstrong', () => {
    const parser = (source: string) => some(emstrong)(input(source, ctx));
    const { context: ctx } = input('', {});

    it('invalid', () => {
      assert.deepStrictEqual(inspect(parser('***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***a'), ctx), [['***', 'a'], '']);
      assert.deepStrictEqual(inspect(parser('***a ***'), ctx), [['***', 'a', ' ', '***'], '']);
      assert.deepStrictEqual(inspect(parser('***a  ***'), ctx), [['***', 'a', ' ', ' ', '***'], '']);
      assert.deepStrictEqual(inspect(parser('***a\n***'), ctx), [['***', 'a', '<br>', '***'], '']);
      assert.deepStrictEqual(inspect(parser('***a\\ ***'), ctx), [['***', 'a', ' ', '***'], '']);
      assert.deepStrictEqual(inspect(parser('***a\\\n***'), ctx), [['***', 'a', '<br>', '***'], '']);
      assert.deepStrictEqual(inspect(parser('*** ***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('*** a***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('*** a ***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***\n***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***\na***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***\\ a***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***\\\na***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('***<wbr>a***'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser(' ***a***'), ctx), undefined);
    });

    it('basic', () => {
      assert.deepStrictEqual(inspect(parser('***a***'), ctx), [['<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***ab***'), ctx), [['<em><strong>ab</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a****'), ctx), [['<em><strong>a</strong></em>'], '*']);
      assert.deepStrictEqual(inspect(parser('***a\nb***'), ctx), [['<em><strong>a<br>b</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a\\\nb***'), ctx), [['<em><strong>a<br>b</strong></em>'], '']);
    });

    it('nest', () => {
      assert.deepStrictEqual(inspect(parser('***`a`***'), ctx), [['<em><strong><code data-src="`a`">a</code></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***(*a*)***'), ctx), [['<em><strong><span class="paren">(<em>a</em>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***(**a**)***'), ctx), [['<em><strong><span class="paren">(<strong>a</strong>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***(***a***)***'), ctx), [['<em><strong><span class="paren">(<em><strong>a</strong></em>)</span></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*'), ctx), [['**', '<em>a</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b'), ctx), [['**', '<em>a</em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b*'), ctx), [['**', '<em>a</em>', 'b'], '*']);
      assert.deepStrictEqual(inspect(parser('***a*b*c'), ctx), [['**', '<em>a</em>', 'b*c'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b*c*'), ctx), [['**', '<em>a</em>', 'b', '<em>c</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b*c**'), ctx), [['**', '<em>a</em>', 'b', '<em>c</em>'], '*']);
      assert.deepStrictEqual(inspect(parser('***a*b*c***'), ctx), [['<strong><em>a</em>b<em>c</em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b**'), ctx), [['<strong><em>a</em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b**c'), ctx), [['<strong><em>a</em>b</strong>'], 'c']);
      assert.deepStrictEqual(inspect(parser('***a**'), ctx), [['*', '<strong>a</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b'), ctx), [['*', '<strong>a</strong>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b*'), ctx), [['<em><strong>a</strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b**'), ctx), [['<em><strong>a</strong>b</em>'], '*']);
      assert.deepStrictEqual(inspect(parser('***a**b**c'), ctx), [['*', '<strong>a</strong>', 'b**c'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b**c*'), ctx), [['<em><strong>a</strong>b**c</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b**c**'), ctx), [['*', '<strong>a</strong>', 'b', '<strong>c</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b**c***'), ctx), [['<em><strong>a</strong>b<strong>c</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a *b****'), ctx), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a\\ *b****'), ctx), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a&Tab;*b****'), ctx), [['<em><strong>a\t<em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a<wbr>*b****'), ctx), [['<em><strong>a<wbr><em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a *b****'), ctx), [['<em><strong>a <em>b</em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a* **b****'), ctx), [['<strong><em>a</em> <strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*\\ **b****'), ctx), [['<strong><em>a</em> <strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*&Tab;**b****'), ctx), [['<strong><em>a</em>\t<strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*<wbr>**b****'), ctx), [['<strong><em>a</em><wbr><strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b **'), ctx), [['**', '<em>a</em>', 'b **'], '']);
      assert.deepStrictEqual(inspect(parser('***a*b\\ **'), ctx), [['**', '<em>a</em>', 'b **'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b*'), ctx), [['<em><strong>a</strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b*c'), ctx), [['<em><strong>a</strong>b</em>'], 'c']);
      assert.deepStrictEqual(inspect(parser('***a**b*c**'), ctx), [['<em><strong>a</strong>b</em>'], 'c**']);
      assert.deepStrictEqual(inspect(parser('***a**b**c***'), ctx), [['<em><strong>a</strong>b<strong>c</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b**c***d'), ctx), [['<em><strong>a</strong>b<strong>c</strong></em>'], 'd']);
      assert.deepStrictEqual(inspect(parser('***a** *b**'), ctx), [['<em><strong>a</strong> <em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**\\ *b**'), ctx), [['<em><strong>a</strong> <em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**&Tab;*b**'), ctx), [['<em><strong>a</strong>\t<em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**<wbr>*b**'), ctx), [['<em><strong>a</strong><wbr><em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b *'), ctx), [['*', '<strong>a</strong>', 'b *'], '']);
      assert.deepStrictEqual(inspect(parser('***a**b\\ *'), ctx), [['*', '<strong>a</strong>', 'b *'], '']);
      assert.deepStrictEqual(inspect(parser('***a*'), ctx), [['**', '<em>a</em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a**'), ctx), [['*', '<strong>a</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('***a***'), ctx), [['<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('***a***b'), ctx), [['<em><strong>a</strong></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser('***a****'), ctx), [['<em><strong>a</strong></em>'], '*']);
      assert.deepStrictEqual(inspect(parser('***a*****'), ctx), [['<em><strong>a</strong></em>'], '**']);
      assert.deepStrictEqual(inspect(parser('***a******'), ctx), [['<em><strong>a</strong></em>'], '***']);
      assert.deepStrictEqual(inspect(parser('****a***'), ctx), [['*', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('****a***b'), ctx), [['*', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('****a***b*'), ctx), [['<em><em><strong>a</strong></em>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser('****a****'), ctx), [['<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('****a****b'), ctx), [['<em><em><strong>a</strong></em></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser('*****a***'), ctx), [['**', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('*****a***b'), ctx), [['**', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('*****a***b**'), ctx), [['<strong><em><strong>a</strong></em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('*****a****'), ctx), [['*', '<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('*****a****b'), ctx), [['*', '<em><em><strong>a</strong></em></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('*****a****b*'), ctx), [['<em><em><em><strong>a</strong></em></em>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser('*****a*****'), ctx), [['<strong><em><strong>a</strong></em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('******a***'), ctx), [['***', '<em><strong>a</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('******a***b'), ctx), [['***', '<em><strong>a</strong></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('******a****'), ctx), [['**', '<em><em><strong>a</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser('******a****b'), ctx), [['**', '<em><em><strong>a</strong></em></em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('******a****b**'), ctx), [['<strong><em><em><strong>a</strong></em></em>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser('******a*****'), ctx), [['*', '<strong><em><strong>a</strong></em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser('******a*****b'), ctx), [['*', '<strong><em><strong>a</strong></em></strong>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('******a*****b*'), ctx), [['<em><strong><em><strong>a</strong></em></strong>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser('******a******'), ctx), [['<em><strong><em><strong>a</strong></em></strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser('******a******b'), ctx), [['<em><strong><em><strong>a</strong></em></strong></em>'], 'b']);
      assert.deepStrictEqual(inspect(parser('******a*b'), ctx), [['***', '**', '<em>a</em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser('******a*b *'), ctx), [['***', '**', '<em>a</em>', 'b *'], '']);
      assert.deepStrictEqual(inspect(parser('******a*b **'), ctx), [['***', '**', '<em>a</em>', 'b **'], '']);
      assert.deepStrictEqual(inspect(parser('******a*b ***'), ctx), [['***', '**', '<em>a</em>', 'b ***'], '']);
      assert.deepStrictEqual(inspect(parser('******a*b ****'), ctx), [['***', '**', '<em>a</em>', 'b ****'], '']);
      assert.deepStrictEqual(inspect(parser('******a*b *****'), ctx), [['***', '**', '<em>a</em>', 'b *****'], '']);
    });

  });

});
