import { math } from './math';
import { some } from '../../combinator';
import { input } from '../../combinator/data/parser';
import { Context } from '../context';
import { inspect } from '../../debug.test';

describe('Unit: parser/inline/math', () => {
  describe('math', () => {
    const parser = some(math);

    it('invalid', () => {
      assert.deepStrictEqual(inspect(parser, input('', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$$$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$0 $', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-0, $-1', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-0 and $-1', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-0と$-1', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a $-b', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a\\ $-b', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a $', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a `$`', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a ``$``', new Context())), undefined);
      // (``" + ``" + $-b") or (``"`` + "$-b")
      assert.deepStrictEqual(inspect(parser, input('$-a ``"``"$-b"', new Context())), undefined);
      // (``b`` + "c" + $-d) or (``b``"c" + $-d)
      assert.deepStrictEqual(inspect(parser, input('$-a ``b``"c"$-d', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a"$-b"', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a\\"$-b\\"', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a($-b)', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a\\($-b\\)', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a[$-b]', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a\\[$-b\\]', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$-a{$-b}', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a{$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a$b', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a$b$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$ $', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$ a$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$ a $', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$\n$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a\\$\nb$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$a\\$\\\nb$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$`$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$`a"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$`a"b$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``$"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a"$0', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a""b$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a""$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$```a"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$```a""$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``\n"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a\\$\nb"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a\\$\\\nb"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``\\"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$``a``b"c"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$````""$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$"$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${}', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a} $', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a{b}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a}b}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a}b$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a}b{c}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a}{b}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${$}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${\\}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${\n}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a\\$\nb}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('${a\\$\\\nb}$', new Context())), undefined);
      assert.deepStrictEqual(inspect(parser, input('$\\begin$', new Context())), [['<span class="invalid" translate="no">$\\begin$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\huge0$', new Context())), [['<span class="invalid" translate="no">$\\huge0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\Begin$', new Context())), [['<span class="invalid" translate="no">$\\Begin$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\begin{}$', new Context())), [['<span class="invalid" translate="no">$\\begin{}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${\\begin}$', new Context())), [['<span class="invalid" translate="no">${\\begin}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$http://host$', new Context())), [['<span class="invalid" translate="no">$http://host$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${http://host}$', new Context())), [['<span class="invalid" translate="no">${http://host}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input(' ${a}$', new Context())), undefined);
    });

    it('basic', () => {
      assert.deepStrictEqual(inspect(parser, input('$0$', new Context())), [['<span class="math" translate="no" data-src="$0$">$0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$0$$', new Context())), [['<span class="math" translate="no" data-src="$0$">$0$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser, input('$00$', new Context())), [['<span class="math" translate="no" data-src="$00$">$00$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$-0$', new Context())), [['<span class="math" translate="no" data-src="$-0$">$-0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$0-1$', new Context())), [['<span class="math" translate="no" data-src="$0-1$">$0-1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$0+1$', new Context())), [['<span class="math" translate="no" data-src="$0+1$">$0+1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$0*1$', new Context())), [['<span class="math" translate="no" data-src="$0*1$">$0*1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$0/1$', new Context())), [['<span class="math" translate="no" data-src="$0/1$">$0/1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a$', new Context())), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a$$', new Context())), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser, input('$a-b$', new Context())), [['<span class="math" translate="no" data-src="$a-b$">$a-b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a+b$', new Context())), [['<span class="math" translate="no" data-src="$a+b$">$a+b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a*b$', new Context())), [['<span class="math" translate="no" data-src="$a*b$">$a*b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a/b$', new Context())), [['<span class="math" translate="no" data-src="$a/b$">$a/b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input(`$a'$`, new Context())), [[`<span class="math" translate="no" data-src="$a'$">$a'$</span>`], '']);
      assert.deepStrictEqual(inspect(parser, input(`$a''$`, new Context())), [[`<span class="math" translate="no" data-src="$a''$">$a''$</span>`], '']);
      assert.deepStrictEqual(inspect(parser, input('$a$[A](a)', new Context())), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '[A](a)']);
      assert.deepStrictEqual(inspect(parser, input('$A$', new Context())), [['<span class="math" translate="no" data-src="$A$">$A$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$-a$', new Context())), [['<span class="math" translate="no" data-src="$-a$">$-a$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\$$', new Context())), [['<span class="math" translate="no" data-src="$\\$$">$\\$$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\Pi$', new Context())), [['<span class="math" translate="no" data-src="$\\Pi$">$\\Pi$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\ 0$', new Context())), [['<span class="math" translate="no" data-src="$\\ 0$">$\\ 0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$\\\\0$', new Context())), [['<span class="math" translate="no" data-src="$\\\\0$">$\\\\0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$|1|$', new Context())), [['<span class="math" translate="no" data-src="$|1|$">$|1|$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$[0,1)$]', new Context())), [['<span class="math" translate="no" data-src="$[0,1)$">$[0,1)$</span>'], ']']);
      assert.deepStrictEqual(inspect(parser, input('$(0, 1]$)', new Context())), [['<span class="math" translate="no" data-src="$(0, 1]$">$(0, 1]$</span>'], ')']);
      assert.deepStrictEqual(inspect(parser, input('$\\{0,1\\}$', new Context())), [['<span class="math" translate="no" data-src="$\\{0,1\\}$">$\\{0,1\\}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$n=1$', new Context())), [['<span class="math" translate="no" data-src="$n=1$">$n=1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$n<m$', new Context())), [['<span class="math" translate="no" data-src="$n&lt;m$">$n&lt;m$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$n>m$', new Context())), [['<span class="math" translate="no" data-src="$n&gt;m$">$n&gt;m$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$E = mc^2$', new Context())), [['<span class="math" translate="no" data-src="$E = mc^2$">$E = mc^2$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$f(x)$', new Context())), [['<span class="math" translate="no" data-src="$f(x)$">$f(x)$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$f: x \\to y$', new Context())), [['<span class="math" translate="no" data-src="$f: x \\to y$">$f: x \\to y$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$k$\\-space', new Context())), [['<span class="math" translate="no" data-src="$k$">$k$</span>'], '\\-space']);
      assert.deepStrictEqual(inspect(parser, input('$a{b}$', new Context())), [['<span class="math" translate="no" data-src="$a{b}$">$a{b}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$a\\{$\\}', new Context())), [['<span class="math" translate="no" data-src="$a\\{$">$a\\{$</span>'], '\\}']);
      assert.deepStrictEqual(inspect(parser, input('${}$', new Context())), [['<span class="math" translate="no" data-src="${}$">${}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${ }$', new Context())), [['<span class="math" translate="no" data-src="${ }$">${ }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${a}$', new Context())), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${a}$$', new Context())), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser, input('${a}$0', new Context())), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '0']);
      assert.deepStrictEqual(inspect(parser, input('${a}$b', new Context())), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], 'b']);
      assert.deepStrictEqual(inspect(parser, input('${ab}$', new Context())), [['<span class="math" translate="no" data-src="${ab}$">${ab}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${a b}$', new Context())), [['<span class="math" translate="no" data-src="${a b}$">${a b}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${a }$', new Context())), [['<span class="math" translate="no" data-src="${a }$">${a }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${ a}$', new Context())), [['<span class="math" translate="no" data-src="${ a}$">${ a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${ a }$', new Context())), [['<span class="math" translate="no" data-src="${ a }$">${ a }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${``"}$', new Context())), [['<span class="math" translate="no" data-src="${``&quot;}$">${``"}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${\\a}$', new Context())), [['<span class="math" translate="no" data-src="${\\a}$">${\\a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${\\$}$', new Context())), [['<span class="math" translate="no" data-src="${\\$}$">${\\$}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${\\\\}$', new Context())), [['<span class="math" translate="no" data-src="${\\\\}$">${\\\\}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${あ}$', new Context())), [['<span class="math" translate="no" data-src="${あ}$">${あ}$</span>'], '']);
    });

    it('nest', () => {
      assert.deepStrictEqual(inspect(parser, input('${*a*}$', new Context())), [['<span class="math" translate="no" data-src="${*a*}$">${*a*}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${<wbr>}$', new Context())), [['<span class="math" translate="no" data-src="${&lt;wbr&gt;}$">${&lt;wbr&gt;}$</span>'], '']);
    });

  });

});
