import { math } from './math';
import { some } from '../../combinator';
import { input } from '../../combinator/data/parser';
import { inspect } from '../../debug.test';

describe('Unit: parser/inline/math', () => {
  describe('math', () => {
    const parser = (source: string) => some(math)(input(source, ctx));
    const { context: ctx } = input('', {});

    it('invalid', () => {
      assert.deepStrictEqual(inspect(parser(''), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$$$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$0 $'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-0, $-1'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-0 and $-1'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-0と$-1'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a $-b'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a\\ $-b'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a $'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a `$`'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a ``$``'), ctx), undefined);
      // (``" + ``" + $-b") or (``"`` + "$-b")
      assert.deepStrictEqual(inspect(parser('$-a ``"``"$-b"'), ctx), undefined);
      // (``b`` + "c" + $-d) or (``b``"c" + $-d)
      assert.deepStrictEqual(inspect(parser('$-a ``b``"c"$-d'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a"$-b"'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a\\"$-b\\"'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a($-b)'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a\\($-b\\)'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a[$-b]'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a\\[$-b\\]'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$-a{$-b}'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a{$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a$b'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a$b$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$ $'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$ a$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$ a $'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$\n$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a\\$\nb$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$a\\$\\\nb$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$`$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$`a"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$`a"b$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``$"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a"$0'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a""b$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a""$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$```a"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$```a""$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``\n"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a\\$\nb"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a\\$\\\nb"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``\\"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$``a``b"c"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$````""$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$"$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${}'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a} $'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a{b}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a}b}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a}b$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a}b{c}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a}{b}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${$}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${\\}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${\n}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a\\$\nb}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('${a\\$\\\nb}$'), ctx), undefined);
      assert.deepStrictEqual(inspect(parser('$\\begin$'), ctx), [['<span class="invalid" translate="no">$\\begin$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\huge0$'), ctx), [['<span class="invalid" translate="no">$\\huge0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\Begin$'), ctx), [['<span class="invalid" translate="no">$\\Begin$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\begin{}$'), ctx), [['<span class="invalid" translate="no">$\\begin{}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${\\begin}$'), ctx), [['<span class="invalid" translate="no">${\\begin}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$http://host$'), ctx), [['<span class="invalid" translate="no">$http://host$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${http://host}$'), ctx), [['<span class="invalid" translate="no">${http://host}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser(' ${a}$'), ctx), undefined);
    });

    it('basic', () => {
      assert.deepStrictEqual(inspect(parser('$0$'), ctx), [['<span class="math" translate="no" data-src="$0$">$0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$0$$'), ctx), [['<span class="math" translate="no" data-src="$0$">$0$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser('$00$'), ctx), [['<span class="math" translate="no" data-src="$00$">$00$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$-0$'), ctx), [['<span class="math" translate="no" data-src="$-0$">$-0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$0-1$'), ctx), [['<span class="math" translate="no" data-src="$0-1$">$0-1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$0+1$'), ctx), [['<span class="math" translate="no" data-src="$0+1$">$0+1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$0*1$'), ctx), [['<span class="math" translate="no" data-src="$0*1$">$0*1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$0/1$'), ctx), [['<span class="math" translate="no" data-src="$0/1$">$0/1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a$'), ctx), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a$$'), ctx), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser('$a-b$'), ctx), [['<span class="math" translate="no" data-src="$a-b$">$a-b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a+b$'), ctx), [['<span class="math" translate="no" data-src="$a+b$">$a+b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a*b$'), ctx), [['<span class="math" translate="no" data-src="$a*b$">$a*b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a/b$'), ctx), [['<span class="math" translate="no" data-src="$a/b$">$a/b$</span>'], '']);
      assert.deepStrictEqual(inspect(parser(`$a'$`), ctx), [[`<span class="math" translate="no" data-src="$a'$">$a'$</span>`], '']);
      assert.deepStrictEqual(inspect(parser(`$a''$`), ctx), [[`<span class="math" translate="no" data-src="$a''$">$a''$</span>`], '']);
      assert.deepStrictEqual(inspect(parser('$a$[A](a)'), ctx), [['<span class="math" translate="no" data-src="$a$">$a$</span>'], '[A](a)']);
      assert.deepStrictEqual(inspect(parser('$A$'), ctx), [['<span class="math" translate="no" data-src="$A$">$A$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$-a$'), ctx), [['<span class="math" translate="no" data-src="$-a$">$-a$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\$$'), ctx), [['<span class="math" translate="no" data-src="$\\$$">$\\$$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\Pi$'), ctx), [['<span class="math" translate="no" data-src="$\\Pi$">$\\Pi$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\ 0$'), ctx), [['<span class="math" translate="no" data-src="$\\ 0$">$\\ 0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$\\\\0$'), ctx), [['<span class="math" translate="no" data-src="$\\\\0$">$\\\\0$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$|1|$'), ctx), [['<span class="math" translate="no" data-src="$|1|$">$|1|$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$[0,1)$]'), ctx), [['<span class="math" translate="no" data-src="$[0,1)$">$[0,1)$</span>'], ']']);
      assert.deepStrictEqual(inspect(parser('$(0, 1]$)'), ctx), [['<span class="math" translate="no" data-src="$(0, 1]$">$(0, 1]$</span>'], ')']);
      assert.deepStrictEqual(inspect(parser('$\\{0,1\\}$'), ctx), [['<span class="math" translate="no" data-src="$\\{0,1\\}$">$\\{0,1\\}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$n=1$'), ctx), [['<span class="math" translate="no" data-src="$n=1$">$n=1$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$n<m$'), ctx), [['<span class="math" translate="no" data-src="$n&lt;m$">$n&lt;m$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$n>m$'), ctx), [['<span class="math" translate="no" data-src="$n&gt;m$">$n&gt;m$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$E = mc^2$'), ctx), [['<span class="math" translate="no" data-src="$E = mc^2$">$E = mc^2$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$f(x)$'), ctx), [['<span class="math" translate="no" data-src="$f(x)$">$f(x)$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$f: x \\to y$'), ctx), [['<span class="math" translate="no" data-src="$f: x \\to y$">$f: x \\to y$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$k$\\-space'), ctx), [['<span class="math" translate="no" data-src="$k$">$k$</span>'], '\\-space']);
      assert.deepStrictEqual(inspect(parser('$a{b}$'), ctx), [['<span class="math" translate="no" data-src="$a{b}$">$a{b}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('$a\\{$\\}'), ctx), [['<span class="math" translate="no" data-src="$a\\{$">$a\\{$</span>'], '\\}']);
      assert.deepStrictEqual(inspect(parser('${}$'), ctx), [['<span class="math" translate="no" data-src="${}$">${}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${ }$'), ctx), [['<span class="math" translate="no" data-src="${ }$">${ }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${a}$'), ctx), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${a}$$'), ctx), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '$']);
      assert.deepStrictEqual(inspect(parser('${a}$0'), ctx), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], '0']);
      assert.deepStrictEqual(inspect(parser('${a}$b'), ctx), [['<span class="math" translate="no" data-src="${a}$">${a}$</span>'], 'b']);
      assert.deepStrictEqual(inspect(parser('${ab}$'), ctx), [['<span class="math" translate="no" data-src="${ab}$">${ab}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${a b}$'), ctx), [['<span class="math" translate="no" data-src="${a b}$">${a b}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${a }$'), ctx), [['<span class="math" translate="no" data-src="${a }$">${a }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${ a}$'), ctx), [['<span class="math" translate="no" data-src="${ a}$">${ a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${ a }$'), ctx), [['<span class="math" translate="no" data-src="${ a }$">${ a }$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${``"}$'), ctx), [['<span class="math" translate="no" data-src="${``&quot;}$">${``"}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${\\a}$'), ctx), [['<span class="math" translate="no" data-src="${\\a}$">${\\a}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${\\$}$'), ctx), [['<span class="math" translate="no" data-src="${\\$}$">${\\$}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${\\\\}$'), ctx), [['<span class="math" translate="no" data-src="${\\\\}$">${\\\\}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${あ}$'), ctx), [['<span class="math" translate="no" data-src="${あ}$">${あ}$</span>'], '']);
    });

    it('nest', () => {
      assert.deepStrictEqual(inspect(parser('${*a*}$'), ctx), [['<span class="math" translate="no" data-src="${*a*}$">${*a*}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser('${<wbr>}$'), ctx), [['<span class="math" translate="no" data-src="${&lt;wbr&gt;}$">${&lt;wbr&gt;}$</span>'], '']);
    });

  });

});
