import { inline } from './inline';
import { some } from '../combinator';
import { input } from './context';
import { inspect } from '../debug.test';

describe('Unit: parser/inline', () => {
  describe('inline', () => {
    const parser = some(inline);

    it('empty', () => {
      assert.deepStrictEqual(inspect(parser, input('')), undefined);
    });

    it('escape', () => {
      assert.deepStrictEqual(inspect(parser, input('\\0')), [['0'], '']);
      assert.deepStrictEqual(inspect(parser, input('\\1')), [['1'], '']);
      assert.deepStrictEqual(inspect(parser, input('\\a')), [['a'], '']);
      assert.deepStrictEqual(inspect(parser, input('\\A')), [['A'], '']);
    });

    it('nest', () => {
      assert.deepStrictEqual(inspect(parser, input('あ（Ａ）')), [['あ', '<span class="paren">（Ａ）</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('あ（い）')), [['あ', '<span class="paren">（い）</span>'], '']);
      //assert.deepStrictEqual(inspect(parser, input('='.repeat(1e6))), [['='.repeat(1e6)], '']);
      //assert.deepStrictEqual(inspect(parser, input('*'.repeat(1e6))), [['*'.repeat(1e6)], '']);
      assert.deepStrictEqual(inspect(parser, input('* a*')), [['* a', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('** a**')), [['**', ' a', '**'], '']);
      assert.deepStrictEqual(inspect(parser, input('*** a***')), [['***', ' a', '***'], '']);
      assert.deepStrictEqual(inspect(parser, input('**** a****')), [['****', ' a', '****'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**')), [['<em>a</em>', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b')), [['*', 'a', '**', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b*')), [['<em>a**b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b*c')), [['*', 'a', '**', 'b', '*', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b*c*')), [['*', 'a', '**', 'b', '<em>c</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b**')), [['*', 'a', '<strong>b</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b**c')), [['*', 'a', '<strong>b</strong>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b***')), [['<em>a<strong>b</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b***c')), [['<em>a<strong>b</strong></em>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b****')), [['<em>a<strong>b</strong></em>', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a**b****c')), [['*', 'a', '<strong>b</strong>', '**', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a***b****')), [['<em>a</em>', '<strong>b</strong>', '**'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a***b****c')), [['<em>a</em>', '<strong>b</strong>', '**', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a *b**')), [['<em>a <em>b</em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a *b**c')), [['*', 'a ', '*', 'b', '**', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a **b***')), [['<em>a <strong>b</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a **b***c')), [['<em>a <strong>b</strong></em>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a ***b****')), [['<em>a <em><strong>b</strong></em></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a ***b****c')), [['<em>a <em><strong>b</strong></em></em>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*')), [['**', 'a', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b')), [['**', 'a', '*', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b*')), [['**', 'a', '<em>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b*c')), [['**', 'a', '<em>b</em>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b*c*')), [['**', 'a', '<em>b</em>', 'c', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b*c**')), [['<strong>a<em>b</em>c</strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b**')), [['**', 'a', '<em>b</em>', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b**c')), [['**', 'a', '*', 'b', '**', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b***')), [['<strong>a<em>b</em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a*b***c')), [['<strong>a<em>b</em></strong>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a**b****')), [['<strong>a</strong>', 'b', '****'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a**b****c')), [['<strong>a</strong>', 'b', '****c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a***b*****')), [['<strong>a</strong>', '<em>b</em>', '****'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a***b*****c')), [['<strong>a</strong>', '<em>b</em>', '****c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a *b***')), [['<strong>a <em>b</em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a *b***c')), [['<strong>a <em>b</em></strong>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a **b****')), [['<strong>a <strong>b</strong></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a **b****c')), [['<strong>a <strong>b</strong></strong>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a ***b*****')), [['<strong>a <em><strong>b</strong></em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**a ***b*****c')), [['<strong>a <em><strong>b</strong></em></strong>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*')), [['**', '<em>a</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b')), [['**', '<em>a</em>', 'b'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*')), [['**', '<em>a</em>', 'b', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c')), [['**', '<em>a</em>', 'b', '*', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c*')), [['**', '<em>a</em>', 'b', '<em>c</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c**')), [['**', '<em>a</em>', 'b', '<em>c</em>', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a*b*c***')), [['<strong><em>a</em>b<em>c</em></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('***a**b**c***')), [['<em><strong>a</strong>b<strong>c</strong></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*(*a*)*')), [['<em><span class="paren">(<em>a</em>)</span></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('**(**a**)**')), [['<strong><span class="paren">(<strong>a</strong>)</span></strong>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*[*]')), [['*', '[', '*', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('*<*>')), [['<em>&lt;</em>', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a((b))*')), [['<em>a<sup class="annotation"><span>b</span></sup></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*++ ++*')), [['<em><ins> </ins></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*++ a ++*')), [['<em><ins> a </ins></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*++  a  ++*')), [['<em><ins> a </ins></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*<bdi>`a`</bdi>*')), [['<em><bdi><code data-src="`a`">a</code></bdi></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a"\nb*')), [['<em>a"<br>b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a"\n"("b*')), [['<em>a"<br>"<span class="paren">(</span>"b</em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"*a\nb*')), [['"', '*', 'a', '<br>', 'b', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('"*a\n""b*')), [['"', '*', 'a', '<br>', '"', '"', 'b', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('"a\n"*b"c*')), [['"', 'a', '<br>', '"', '*', 'b', '"', 'c', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('"*a**b\nc**"("*')), [['"', '*', 'a', '**', 'b', '<br>', 'c', '**', '"', '<span class="paren">(</span>', '"', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('[% a"\nb %]')), [['<span class="remark"><input type="checkbox"><span>[% a"<br>b %]</span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"<bdi>"a\n""b</bdi>"')), [['"', '<span class="invalid">&lt;bdi&gt;</span>', '"', 'a', '<br>', '"', '"', 'b', '</bdi', '>', '"'], '']);
      assert.deepStrictEqual(inspect(parser, input('<bdi>*<bdi>a</bdi>*</bdi>')), [['<bdi><em><bdi>a</bdi></em></bdi>'], '']);
      assert.deepStrictEqual(inspect(parser, input('<bdi>[[<bdi>[[a]]</bdi>]]</bdi>')), [['<bdi><sup class="reference"><span><bdi>[[a]]</bdi></span></sup></bdi>'], '']);
      assert.deepStrictEqual(inspect(parser, input('<bdi>[#</bdi>]')), [['<span class="invalid">&lt;bdi&gt;[#&lt;/bdi&gt;]</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"<bdi>("")</bdi>')), [['"', '<span class="invalid">&lt;bdi&gt;(</span>', '"', '"', ')', '</bdi', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('++\na\n++\n~~\nb\n~~\nc')), [['<ins><br>a</ins>', '<br>', '<del><br>b</del>', '<br>', 'c'], '']);
      assert.deepStrictEqual(inspect(parser, input('[@a]')), [['[', '<a class="account" href="/@a">@a</a>', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#1][#2]')), [['<a class="index" href="#index::1">1</a>', '<a class="index" href="#index::2">2</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[$1]')), [['[', '$1', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[$1-2]')), [['[', '$1-2', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[$-1][$-2]')), [['<a class="label" data-label="$-1">$-1</a>', '<a class="label" data-label="$-2">$-2</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$-1, $-2')), [['<a class="label" data-label="$-1">$-1</a>', ', ', '<a class="label" data-label="$-2">$-2</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$-1 and $-2')), [['<a class="label" data-label="$-1">$-1</a>', ' and ', '<a class="label" data-label="$-2">$-2</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('$$-1')), [['$', '<a class="label" data-label="$-1">$-1</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#a]]')), [['<sup class="reference"><span><a class="hashtag" href="/hashtags/a">#a</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[$-1]]')), [['<sup class="reference"><span><a class="label" data-label="$-1">$-1</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#-1]]{b}')), [['<sup class="reference"><span>#-1</span></sup>', '<a class="url" href="b">b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#-1]](b)')), [['<sup class="reference"><span>#-1</span></sup>', '<span class="paren">(b)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#-1]a]{b}')), [['<a class="link" href="b">[#-1]a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#-1]a](b)')), [['[', '<a class="index" href="#index::-1">-1</a>', 'a', ']', '<span class="paren">(b)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#a]{b}')), [['<a class="index" href="#index::a">a</a>', '<a class="url" href="b">b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[@a]{b}')), [['<a class="link" href="b">@a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[http://host]{http://evil}')), [['<a class="invalid">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[http://host]{http://host}')), [['<a class="invalid">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[]{{a}}')), [['[', ']', '<span class="template">{{a}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('![]{{a}}')), [['!', '[', ']', '<span class="template">{{a}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[\n]{a}')), [['[', '<br>', ']', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[\\\n]{a}')), [['[', '<br>', ']', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('{}')), [['{', '}'], '']);
      assert.deepStrictEqual(inspect(parser, input('{a}')), [['<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('{{a}}')), [['<span class="template">{{a}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('!{}')), [['!', '{', '}'], '']);
      assert.deepStrictEqual(inspect(parser, input('!{a}')), [['!', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('!{{a}}')), [['!', '<span class="template">{{a}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('!{{{a}}}')), [['!', '<span class="template">{{{a}}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('!!{a}')), [['!', '!', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${a}')), [['$', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${{a}}')), [['$', '<span class="template">{{a}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('${{{a}}}')), [['$', '<span class="template">{{{a}}}</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('Di$ney Micro$oft')), [['Di', '$ney Micro', '$oft'], '']);
      assert.deepStrictEqual(inspect(parser, input('Di$ney, Micro$oft')), [['Di', '$ney, Micro', '$oft'], '']);
      assert.deepStrictEqual(inspect(parser, input('(((a))')), [['<span class="paren">(<sup class="annotation"><span>a</span></sup></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('((((a))')), [['<span class="paren">(<span class="paren">(<sup class="annotation"><span>a</span></sup></span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('((${))}$')), [['<span class="paren">(<span class="paren">(<span class="math" translate="no" data-src="${))}$">${))}$</span></span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('((a\nb))')), [['<span class="bracket">(<span class="bracket">(a<br>b)</span>)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(((a\nb)))')), [['<span class="bracket">(<span class="bracket">(<span class="bracket">(a<br>b)</span>)</span>)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(([[a] ]))')), [['<sup class="annotation"><span>[[a] ]</span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(([[a] ]{b}))')), [['<sup class="annotation"><span><a class="link" href="b">[a]</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(([["*(*"] ]))')), [['<sup class="annotation"><span>[["*<span class="paren">(*</span>"] ]</span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(([:a\n]')), [['<span class="bracket">(<span class="bracket">(<span class="invalid">[:a\n]</span></span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(({{\n}}')), [['<span class="bracket">(<span class="bracket">(<span class="template">{{<br>}}</span></span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"((""))')), [['"', '<span class="paren">(<span class="paren">(</span></span>', '"', '"', ')', ')'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[a]]')), [['[', '<sup class="reference"><span>a</span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[[a]]')), [['[', '[', '<sup class="reference"><span>a</span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[[a]]]]')), [['<sup class="reference"><span>[[a]]</span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[$-1]]]')), [['<sup class="reference"><span><a class="label" data-label="$-1">$-1</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[]{a}]]')), [['<sup class="reference"><span><a class="url" href="a">a</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[a]{b}]]')), [['<sup class="reference"><span><a class="link" href="b">a</a></span></sup>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[(([a]{#}))]{#}')), [['<a class="link" href="#"><span class="paren">(<span class="paren">([a]{#})</span>)</span></a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[${]]}$')), [['[', '[', '<span class="math" translate="no" data-src="${]]}$">${]]}$</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[a\nb]]')), [['[', '[', 'a', '<br>', 'b', ']', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[a\nb]]]')), [['[', '[', '[', 'a', '<br>', 'b', ']', ']', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('"[[""]]')), [['"', '[', '[', '"', '"', ']', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[==a==]{b}')), [['<a class="link" href="b"><mark>a</mark></a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[a](b)]{c}')), [['<a class="link" href="c"><ruby>a<rp>(</rp><rt>b</rt><rp>)</rp></ruby></a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[[[[[[{a}')), [['[', '[', '[', '[', '[', '[', '[', '<a class="url" href="a">a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('<http://host>')), [['<', '<a class="url" href="http://host" target="_blank">http://host</a>', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[~http://host')), [['[', '~', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[~a@b')), [['[', '~', '<a class="email" href="mailto:a@b">a@b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[~~a~~]')), [['[', '<del>a</del>', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[^http://host')), [['[^', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[^a@b')), [['[^', '<a class="email" href="mailto:a@b">a@b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"[% *"*"*')), [['"', '[%', ' ', '*', '"', '*', '"', '*'], '']);
      assert.deepStrictEqual(inspect(parser, input('"[% "*"* %]')), [['"', '<span class="remark"><input type="checkbox"><span>[% "*"* %]</span></span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"{{""}}')), [['"', '{', '<a class="url" href="&quot;&quot;">""</a>', '}'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#http://host/(<bdi>)]</bdi>')), [['<a class="index" href="#index::http://host/(&lt;bdi&gt;)">http://host/<span class="paren">(<span class="invalid">&lt;bdi&gt;</span>)</span></a>', '</bdi', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#@a/http://host/(<bdi>)]</bdi>')), [['<a class="index" href="#index::@a/http://host/(&lt;bdi&gt;)">@a/http://host/(&lt;bdi&gt;)</a>', '</bdi', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#a|<bdi>]</bdi>')), [['<a class="index" href="#index::a|&lt;bdi&gt;">a|<span class="invalid">&lt;bdi&gt;</span></a>', '</bdi', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[#a|<bdi>]</bdi>')), [['[', '<a class="index" href="#index::a|&lt;bdi&gt;">a|<span class="invalid">&lt;bdi&gt;</span></a>', '</bdi', '>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[*==*]{a}')), [['<a class="link" href="a">*==*</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[]{"}[[""]]}]')), [['<a class="url" href="&quot;">"</a>', '<sup class="reference"><span>""</span></sup>', '}', ']'], '']);
      assert.deepStrictEqual(inspect(parser, input('[ []{"}[[""]]}]')), [['[', ' ', '<a class="url" href="&quot;">"</a>', '<sup class="reference"><span>""</span></sup>', '}', ']'], '']);
    });

    it('uri', () => {
      assert.deepStrictEqual(inspect(parser, input('\nhttp://host')), [['<br>', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('0http://host')), [['0http', '://host'], '']);
      assert.deepStrictEqual(inspect(parser, input('0aAhttp://host')), [['0aAhttp', '://host'], '']);
      assert.deepStrictEqual(inspect(parser, input('?http://host')), [['?', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('0!http://host')), [['0', '!', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('0?http://host')), [['0?', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_http://host')), [['_', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_http://host_')), [['_', '<a class="url" href="http://host" target="_blank">http://host</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('*http://host*')), [['<em><a class="url" href="http://host" target="_blank">http://host</a></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(http://host)')), [['<span class="paren">(<a class="url" href="http://host" target="_blank">http://host</a>)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input('"http://host"')), [['"', '<a class="url" href="http://host" target="_blank">http://host</a>', '"'], '']);
      assert.deepStrictEqual(inspect(parser, input('"http://host""')), [['"', '<a class="url" href="http://host" target="_blank">http://host</a>', '"', '"'], '']);
      assert.deepStrictEqual(inspect(parser, input(' http://host')), [[' ', '<a class="url" href="http://host" target="_blank">http://host</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('あhttp://hostい')), [['あ', '<a class="url" href="http://host" target="_blank">http://host</a>', 'い'], '']);
    });

    it('email', () => {
      assert.deepStrictEqual(inspect(parser, input('a@b')), [['<a class="email" href="mailto:a@b">a@b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_a@b')), [['_', '<a class="email" href="mailto:a@b">a@b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_a@b_')), [['_', '<a class="email" href="mailto:a@b">a@b</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('_a_b@c_')), [['_', '<a class="email" href="mailto:a_b@c">a_b@c</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('*a@b*')), [['<em><a class="email" href="mailto:a@b">a@b</a></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(a@b)')), [['<span class="paren">(<a class="email" href="mailto:a@b">a@b</a>)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input(' a@b')), [[' ', '<a class="email" href="mailto:a@b">a@b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('++a@b++')), [['<ins><a class="email" href="mailto:a@b">a@b</a></ins>'], '']);
      assert.deepStrictEqual(inspect(parser, input('++a++b@c++')), [['<ins>a</ins>', '<a class="email" href="mailto:b@c">b@c</a>', '++'], '']);
    });

    it('channel', () => {
      assert.deepStrictEqual(inspect(parser, input('@a#b')), [['<a class="channel" href="/@a?ch=b">@a#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('@domain/a#b')), [['<a class="channel" href="https://domain/@a?ch=b" target="_blank">@domain/a#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_@a#b')), [['_', '<a class="channel" href="/@a?ch=b">@a#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_@a#b_')), [['_', '<a class="channel" href="/@a?ch=b">@a#b</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input(' @a#b')), [[' ', '<a class="channel" href="/@a?ch=b">@a#b</a>'], '']);
    });

    it('account', () => {
      assert.deepStrictEqual(inspect(parser, input('@a')), [['<a class="account" href="/@a">@a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('@http://host')), [['@', 'http', '://host'], '']);
      assert.deepStrictEqual(inspect(parser, input('_@a')), [['_', '<a class="account" href="/@a">@a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_@a_')), [['_', '<a class="account" href="/@a">@a</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('*@a*')), [['<em><a class="account" href="/@a">@a</a></em>'], '']);
      assert.deepStrictEqual(inspect(parser, input('(@a)')), [['<span class="paren">(<a class="account" href="/@a">@a</a>)</span>'], '']);
      assert.deepStrictEqual(inspect(parser, input(' @a')), [[' ', '<a class="account" href="/@a">@a</a>'], '']);
    });

    it('hashtag', () => {
      assert.deepStrictEqual(inspect(parser, input('#a#')), [['#a', '#'], '']);
      assert.deepStrictEqual(inspect(parser, input('#a#b')), [['#a', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('#a')), [['<a class="hashtag" href="/hashtags/a">#a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('#http://host')), [['#', 'http', '://host'], '']);
      assert.deepStrictEqual(inspect(parser, input('#a\nb\n#c\n[#d]')), [['<a class="hashtag" href="/hashtags/a">#a</a>', '<br>', 'b', '<br>', '<a class="hashtag" href="/hashtags/c">#c</a>', '<br>', '<a class="index" href="#index::d">d</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#a')), [['_', '<a class="hashtag" href="/hashtags/a">#a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#a_')), [['_', '<a class="hashtag" href="/hashtags/a">#a</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#a_b')), [['_', '<a class="hashtag" href="/hashtags/a_b">#a_b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#a_b_')), [['_', '<a class="hashtag" href="/hashtags/a_b">#a_b</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('a#b')), [['a', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('0a#b')), [['0a', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('あ#b')), [['あ', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('あい#b')), [['あい', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('0aあ#b')), [['0aあ', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('0aあい#b')), [['0aあい', '#b'], '']);
      assert.deepStrictEqual(inspect(parser, input('「#あ」')), [['「', '<a class="hashtag" href="/hashtags/あ">#あ</a>', '」'], '']);
      assert.deepStrictEqual(inspect(parser, input('a\n#b')), [['a', '<br>', '<a class="hashtag" href="/hashtags/b">#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('a\\\n#b')), [['a', '<br>', '<a class="hashtag" href="/hashtags/b">#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('((a))#b')), [['<sup class="annotation"><span>a</span></sup>', '<a class="hashtag" href="/hashtags/b">#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[[a]]#b')), [['<sup class="reference"><span>a</span></sup>', '<a class="hashtag" href="/hashtags/b">#b</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('[#a')), [['[', '<a class="hashtag" href="/hashtags/a">#a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('|#a')), [['|', '<a class="hashtag" href="/hashtags/a">#a</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input(' #a')), [[' ', '<a class="hashtag" href="/hashtags/a">#a</a>'], '']);
    });

    it('hashnum', () => {
      assert.deepStrictEqual(inspect(parser, input('#1')), [['<a class="hashnum">#1</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input(`#1'`)), [[`<a class="hashnum">#1</a>`, `'`], '']);
      assert.deepStrictEqual(inspect(parser, input('#1234567890@a')), [['#', '1234567890', '@a'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#1')), [['_', '<a class="hashnum">#1</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#1_')), [['_', '<a class="hashnum">#1</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#1_0')), [['_', '<a class="hashtag" href="/hashtags/1_0">#1_0</a>'], '']);
      assert.deepStrictEqual(inspect(parser, input('_#1_0_')), [['_', '<a class="hashtag" href="/hashtags/1_0">#1_0</a>', '_'], '']);
      assert.deepStrictEqual(inspect(parser, input('「#1」')), [['「', '<a class="hashnum">#1</a>', '」'], '']);
    });

  });

});
